-- Active: 1709286938507@@127.0.0.1@3306@blackjack
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    balance INT NOT NULL DEFAULT 500
);

CREATE TABLE IF NOT EXISTS tokens (
  sessionToken VARCHAR(255) PRIMARY KEY,
  userId INT NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  bet INT NOT NULL,
  turnTime INT NOT NULL,
  playersCount INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  stay BOOLEAN NOT NULL DEFAULT 0,
  gameId INT NOT NULL,
  userId INT NOT NULL,
  FOREIGN KEY (gameId) REFERENCES games(id),
  FOREIGN KEY (userId) REFERENCES users(id)
);  

CREATE TABLE IF NOT EXISTS cards (
  id INT AUTO_INCREMENT PRIMARY KEY,
  value INT NOT NULL,
  suite VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS gamePlayersCards (
  cardId INT NOT NULL,
  playerId INT NOT NULL,
  FOREIGN KEY (cardId) REFERENCES cards(id),
  FOREIGN KEY (playerId) REFERENCES players(id)
);
